# Site settings
title: Bognar.bithub.io
description: A personal blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Josip Bognar
user_description: I am a technology enthusiast who loves development, support and cybersecurity. I often work on projects for some of the biggest tech companies revolving around Azure, Cybersecurity, Virtualization and much much more.
user_title: IT Engineer with focus on Cybersecurity
github_username:  Bognar


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
