# Site settings
title: Bognar.bithub.io
description: A personal blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Josip Bognar
user_description: I am a technology enthusiast who loves development, support and cybersecurity. As a part of my daily job rutine, I work on resolving complex issues in domain of Level 3 engineering, infrastructure assessment projects utilizing NIST, CIS, MITRE and projects to implement new solutions. There is no point of enumerating each solution or platform I am utilizing, so for any interested partys, please get in touch with me.
user_title: AI | ML | Automation | Cybersecurity | Big Data | Cloud
github_username:  Bognar

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
